[program:mariadb]
command=/usr/sbin/mariadbd --user=mysql --datadir=/var/lib/mysql
priority=10
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:redis]
command=/usr/bin/redis-server /etc/redis/erpnext.conf
priority=20
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:gunicorn]
directory=/home/frappe/frappe-bench
command=/home/frappe/frappe-bench/env/bin/gunicorn --chdir=/home/frappe/frappe-bench/sites -b 127.0.0.1:8000 -w 4 --timeout 120 frappe.app:application
user=frappe
priority=30
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:websocket]
directory=/home/frappe/frappe-bench
command=/usr/local/bin/node apps/frappe/socketio.js
user=frappe
priority=30
autorestart=true
stopasgroup=true
killasgroup=true
environment=PORT="9000"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:worker]
directory=/home/frappe/frappe-bench
command=/usr/bin/sudo -H -u frappe /home/frappe/.local/bin/bench worker --queue short,default,long
priority=40
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:scheduler]
directory=/home/frappe/frappe-bench
command=/usr/bin/sudo -H -u frappe /home/frappe/.local/bin/bench schedule
priority=40
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
priority=50
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
